name: CI-Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: dependencies
        run: npm ci
      - name: lint
        run: npm lint
      - name: test
        run: npm test
